site_name: Hacking Websites
nav:
  - Home: index.md
  - Hacking Google: google.md
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages: ["css", "javascript", "html"]
extra_css:
  - css/style.css
